// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Mr_ABC.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Mr_ABC {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=23;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=24;
      Object coder=$fix($invokeMethod(Mr_ABC.class,"createCoder",true,null,new Object[]{}));
      $line=26;
      if ($bool((!$opEqualY($invokeField("length",args),0)&&$opEqualY(((java.lang.String[])args)[$int(0)],"GUI")))) {
        $line=27;
        GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,coder));
      }
      else {
        $line=29;
        Utilities.test($cast(gold.structures.automaton.IAutomaton.class,coder));
      }
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Mr_ABC.class,"main",$line);
    }
  }
  public static Object createCoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=37;
      Object L=$fix(GCollections.asSet('a','b','c'));
      $line=39;
      Object Q=$fix($opUnionY($opCartsY(new Object[]{$opPwsetY(L),GCollections.asSet(0)}),GCollections.asSet("end")));
      $line=40;
      Object In=$fix(L);
      $line=41;
      Object Out=$fix($opIntvlY('0','7'));
      $line=42;
      Object q0=$fix(GCollections.asList(GCollections.emptySet(),0));
      $line=43;
      Object F=$fix(GCollections.asSet(GCollections.asList(GCollections.emptySet(),0)));
      $line=45;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,In,Out,q0,F,new GMethod(Mr_ABC.class,"d"),new GMethod(Mr_ABC.class,"g"),new GMethod(Mr_ABC.class,"h")});
      if (true) break $try;
      $line=46;
      $rethrow(new RuntimeException("The function \"createCoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Mr_ABC.class,"createCoder",$line);
    }
    return $result;
  }
  public static Object d(Object q, Object x) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=49;
      $result=q;
      if (true) break $try;
      $line=50;
      $rethrow(new RuntimeException("The function \"d(q:Object,x:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Mr_ABC.class,"d",$line);
    }
    return $result;
  }
  public static Object d(java.lang.Iterable $v1, Object x) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v2=GCollections.unmodifiableCollection($v1).iterator();
      Object S=$v2.next();
      Object q=$v2.next();
      $line=53;
      System.out.println($message(new Object[]{GCollections.asList(S,q)}));
      $line=54;
      if (($opEqualY(q,0)&&$bool((($opEqualY(x,'a')||$opEqualY(x,'b'))||$opEqualY(x,'c'))))) {
        $line=55;
        if (($opEqualY(x,'a')&&!$opMembrY(x,S))) {
          $line=56;
          $result=GCollections.asList($opUnionY(S,GCollections.asSet(x)),0);
          if (true) break $try;
        }
        else {
          $line=57;
          if (($opEqualY(x,'b')&&!$opMembrY(x,S))) {
            $line=58;
            $result=GCollections.asList($opUnionY(S,GCollections.asSet(x)),0);
            if (true) break $try;
          }
          else {
            $line=59;
            if (($opEqualY(x,'c')&&!$opMembrY(x,S))) {
              $line=60;
              $result=GCollections.asList($opUnionY(S,GCollections.asSet(x)),0);
              if (true) break $try;
            }
            else {
              $line=61;
              if (($opEqualY(x,'a')&&$opMembrY(x,S))) {
                $line=62;
                $result=GCollections.asList($opDiffeY(S,GCollections.asSet(x)),0);
                if (true) break $try;
              }
              else {
                $line=63;
                if (($opEqualY(x,'b')&&$opMembrY(x,S))) {
                  $line=64;
                  $result=GCollections.asList($opDiffeY(S,GCollections.asSet(x)),0);
                  if (true) break $try;
                }
                else {
                  $line=65;
                  if (($opEqualY(x,'c')&&$opMembrY(x,S))) {
                    $line=66;
                    $result=GCollections.asList($opDiffeY(S,GCollections.asSet(x)),0);
                    if (true) break $try;
                  }
                }
              }
            }
          }
        }
      }
      else {
        $line=69;
        $result="end";
        if (true) break $try;
      }
      $line=71;
      $rethrow(new RuntimeException("The function \"d(\u27E8S,q\u27E9:java.lang.Iterable,x:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Mr_ABC.class,"d",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object x) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=74;
      $result="";
      if (true) break $try;
      $line=75;
      $rethrow(new RuntimeException("The function \"h(q:Object,x:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Mr_ABC.class,"h",$line);
    }
    return $result;
  }
  public static Object g(java.lang.Iterable $v3) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v4=GCollections.unmodifiableCollection($v3).iterator();
      Object S=$v4.next();
      Object q=$v4.next();
      $line=78;
      if ($bool(GCollections.asList(GCollections.asSet('c'),0))) {
        $line=79;
        $result='1';
        if (true) break $try;
      }
      else {
        $line=80;
        if ($bool(GCollections.asList(GCollections.asSet('b'),0))) {
          $line=81;
          $result='2';
          if (true) break $try;
        }
        else {
          $line=82;
          if ($bool(GCollections.asList($opPwsetY(GCollections.asSet('b','c')),0))) {
            $line=83;
            $result='3';
            if (true) break $try;
          }
          else {
            $line=84;
            if ($bool(GCollections.asList(GCollections.asSet('a'),0))) {
              $line=85;
              $result='4';
              if (true) break $try;
            }
            else {
              $line=86;
              if ($bool(GCollections.asList($opPwsetY(GCollections.asSet('a','c')),0))) {
                $line=87;
                $result='5';
                if (true) break $try;
              }
              else {
                $line=88;
                if ($bool(GCollections.asList($opPwsetY(GCollections.asSet('a','b')),0))) {
                  $line=89;
                  $result='6';
                  if (true) break $try;
                }
                else {
                  $line=90;
                  if ($bool(GCollections.asList($opPwsetY(GCollections.asSet('a','b','c')),0))) {
                    $line=91;
                    $result='7';
                    if (true) break $try;
                  }
                  else {
                    $line=92;
                    if ($bool(GCollections.asList(GCollections.asSet(GCollections.emptySet()),0))) {
                      $line=93;
                      $result='0';
                      if (true) break $try;
                    }
                    else {
                      $line=95;
                      $result="";
                      if (true) break $try;
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=97;
      $rethrow(new RuntimeException("The function \"g(\u27E8S,q\u27E9:java.lang.Iterable)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Mr_ABC.class,"g",$line);
    }
    return $result;
  }
}
