// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/DivisionAlgorithm.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class DivisionAlgorithm {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=13;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,DivisionAlgorithm.createAutomaton()));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,DivisionAlgorithm.class,"main",$line);
    }
  }
  public static IPushdownAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=16;
      Object \u03A3=$fix(GCollections.asSet('2','0','3','4','5','x','q','r','=','+','*'));
      $line=18;
      Object Q=$fix($opUnionY($opUnionY($opUnionY($opUnionY(GCollections.asSet(0,1,2),GCollections.asSet("D2","D3","D4","D5")),GCollections.asSet("Q2","Q3","Q4","Q5")),GCollections.asSet("R1","R2","R3","R4")),GCollections.asSet("Z2","Z3","Z4","Z5","F")));
      $line=20;
      Object \u0393=$fix(GCollections.asSet('x','$'));
      $line=21;
      Object q_0=$fix(0);
      $line=22;
      Object F=$fix(GCollections.asSet("F"));
      $line=23;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=26;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=27;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,"x")),new Object[]{"x"});
      $line=28;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,2,$cast(java.lang.String.class,"x")),new Object[]{"x"});
      $line=31;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,"D2",$cast(java.lang.String.class,"=2*")),new Object[]{});
      $line=34;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("D2","Z2",$cast(java.lang.String.class,"0")),new Object[]{});
      $line=35;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Z2","R1",$cast(java.lang.String.class,"+r")),new Object[]{"x"});
      $line=38;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("D2","Q2",$cast(java.lang.String.class,"q")),new Object[]{"xx"});
      $line=39;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q2","Q2",$cast(java.lang.String.class,"q")),new Object[]{"xx"});
      $line=42;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q2","R1",$cast(java.lang.String.class,"+r")),new Object[]{"x"});
      $line=43;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("R1","F",$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=45;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q2","F",$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=48;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,"D3",$cast(java.lang.String.class,"=3*")),new Object[]{});
      $line=51;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("D3","Z3",$cast(java.lang.String.class,"0")),new Object[]{});
      $line=52;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Z3","R1",$cast(java.lang.String.class,"+r")),new Object[]{"x"});
      $line=53;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Z3","R2",$cast(java.lang.String.class,"+rr")),new Object[]{"xx"});
      $line=56;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("D3","Q3",$cast(java.lang.String.class,"q")),new Object[]{"xxx"});
      $line=57;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q3","Q3",$cast(java.lang.String.class,"q")),new Object[]{"xxx"});
      $line=60;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q3","R1",$cast(java.lang.String.class,"+r")),new Object[]{"x"});
      $line=61;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q3","R2",$cast(java.lang.String.class,"+rr")),new Object[]{"xx"});
      $line=62;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("R2","F",$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=64;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q3","F",$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=67;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,"D4",$cast(java.lang.String.class,"=4*")),new Object[]{});
      $line=70;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("D4","Z4",$cast(java.lang.String.class,"0")),new Object[]{});
      $line=71;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Z4","R1",$cast(java.lang.String.class,"+r")),new Object[]{"x"});
      $line=72;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Z4","R2",$cast(java.lang.String.class,"+rr")),new Object[]{"xx"});
      $line=73;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Z4","R3",$cast(java.lang.String.class,"+rrr")),new Object[]{"xxx"});
      $line=76;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("D4","Q4",$cast(java.lang.String.class,"q")),new Object[]{"xxxx"});
      $line=77;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q4","Q4",$cast(java.lang.String.class,"q")),new Object[]{"xxxx"});
      $line=80;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q4","R1",$cast(java.lang.String.class,"+r")),new Object[]{"x"});
      $line=81;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q4","R2",$cast(java.lang.String.class,"+rr")),new Object[]{"xx"});
      $line=82;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q4","R3",$cast(java.lang.String.class,"+rrr")),new Object[]{"xxx"});
      $line=83;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("R3","F",$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=85;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q4","F",$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=88;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,"D5",$cast(java.lang.String.class,"=5*")),new Object[]{});
      $line=91;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("D5","Z5",$cast(java.lang.String.class,"0")),new Object[]{});
      $line=92;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Z5","R1",$cast(java.lang.String.class,"+r")),new Object[]{"x"});
      $line=93;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Z5","R2",$cast(java.lang.String.class,"+rr")),new Object[]{"xx"});
      $line=94;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Z5","R3",$cast(java.lang.String.class,"+rrr")),new Object[]{"xxx"});
      $line=95;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Z5","R4",$cast(java.lang.String.class,"+rrrr")),new Object[]{"xxxx"});
      $line=98;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("D5","Q5",$cast(java.lang.String.class,"q")),new Object[]{"xxxxx"});
      $line=99;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q5","Q5",$cast(java.lang.String.class,"q")),new Object[]{"xxxxx"});
      $line=102;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q5","R1",$cast(java.lang.String.class,"+r")),new Object[]{"x"});
      $line=103;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q5","R2",$cast(java.lang.String.class,"+rr")),new Object[]{"xx"});
      $line=104;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q5","R3",$cast(java.lang.String.class,"+rrr")),new Object[]{"xxx"});
      $line=105;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q5","R4",$cast(java.lang.String.class,"+rrrr")),new Object[]{"xxxx"});
      $line=106;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("R4","F",$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=108;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Q5","F",$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=110;
      $result=M;
      if (true) break $try;
      $line=111;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,DivisionAlgorithm.class,"createAutomaton",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
}
